.TH "Clasificacion" 3 "Mon Jun 5 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clasificacion \- Clase Clasificador, contiene todos los métodos y variables necesarias de Machine Learning por la librería Scikit-Learn\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Clase Clasificador, contiene todos los métodos y variables necesarias de Machine Learning por la librería Scikit-Learn\&. 

Clase ClasificadorML, Clase hija de Clasificador que contiene ciertos métodos para mantener los datos y así lograr hacer funcionar los métodos de Clasificador\&.
.PP
Clase ClasificadorAR, Clase hija de Clasificador que contiene ciertos métodos para transformar datos a array y así lograr hacer funcionar los métodos de Clasificador\&.
.PP
\fBAuthor\fP
.RS 4
Roberto Carlos García Cruz\&. 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
'%A %d-%m-%Y' 1-6-2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
