.TH "Controlador.Controlador.Controlador" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controlador.Controlador.Controlador
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBiniciar\fP (self)"
.br
.ti -1c
.RI "def \fBseleccionar_archivo_test\fP (self)"
.br
.ti -1c
.RI "def \fBseleccionar_archivo_entrenamiento\fP (self)"
.br
.ti -1c
.RI "def \fBdefinir_variables\fP (self)"
.br
.ti -1c
.RI "def \fBanadir_variables\fP (self)"
.br
.ti -1c
.RI "def \fBseleccionar_bag_words\fP (self, frase)"
.br
.ti -1c
.RI "def \fBseleccionar_algoritmo\fP (self, frase)"
.br
.ti -1c
.RI "def \fBmostrar_tabla\fP (self, dataset, anchura, max_anchura_celda)"
.br
.ti -1c
.RI "def \fBentrenamiento_datasets\fP (self)"
.br
.ti -1c
.RI "def \fBclasificar\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvista_\fP"
.br
.ti -1c
.RI "\fBmodelo_\fP"
.br
.ti -1c
.RI "\fBboton_variables\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
