.TH "Controlador.Controlador.Controlador" 3 "Mon Jun 5 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controlador.Controlador.Controlador
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.RI "Constructor de \fBControlador\fP\&. "
.ti -1c
.RI "def \fBiniciar\fP (self)"
.br
.RI "Inicia la aplicación\&. "
.ti -1c
.RI "def \fBanadir_funcionalidades\fP (self)"
.br
.RI "Añade las funcionalidades a cada uno de los botones\&. "
.ti -1c
.RI "def \fBseleccionar_archivo_test\fP (self)"
.br
.RI "Permite seleccionar el archivo del conjunto de test\&. "
.ti -1c
.RI "def \fBseleccionar_archivo_entrenamiento\fP (self)"
.br
.RI "Permite seleccionar el archivo del conjunto de entrenamiento\&. "
.ti -1c
.RI "def \fBrealizar_configuracion\fP (self)"
.br
.RI "Se encarga de abrir la ventana de configuración y actualizar las variables\&. "
.ti -1c
.RI "def \fBmostrar_tabla\fP (self, dataset, anchura, max_anchura_celda)"
.br
.RI "Muestra una ventana con formato de dataset, con la información dada en los parámetros\&. "
.ti -1c
.RI "def \fBentrenamiento_datasets\fP (self)"
.br
.RI "LLama al entrenamiento del modelo y controla los errores\&. "
.ti -1c
.RI "def \fBclasificar\fP (self)"
.br
.RI "LLama a la clasificación del modelo y controla los errores\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def Controlador\&.Controlador\&.Controlador\&.mostrar_tabla ( self,  dataset,  anchura,  max_anchura_celda)"

.PP
Muestra una ventana con formato de dataset, con la información dada en los parámetros\&. 
.PP
\fBParameters\fP
.RS 4
\fIdataset\fP [Panda dataset] Dataset a mostrar\&. 
.br
\fIanchura\fP [Int] Anchura de la ventana\&. 
.br
\fImax_anchura_celda\fP [Int] Anchura máxima de las celdas\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
