.TH "Datos" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Datos \- Clase Dataset, actúa como dataset para el almacenamiento de datos y para facilitar su mantenimiento\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Clase Dataset, actúa como dataset para el almacenamiento de datos y para facilitar su mantenimiento\&. 


.PP
\fBAuthor\fP
.RS 4
Roberto Carlos García Cruz\&. 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
'%A %d-%m-%Y' 1-6-2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
