.TH "Lectura" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lectura \- Clase Lector, clase padre de la cual pueden salir distintos tipos de lectores (CSV, JSON, étc\&.), contiene funciones básicas\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Clase Lector, clase padre de la cual pueden salir distintos tipos de lectores (CSV, JSON, étc\&.), contiene funciones básicas\&. 

Clase LectorCSV, clase hija de la clase Lector, lee archivos CSV mediante la librería panda\&.
.PP
\fBAuthor\fP
.RS 4
Roberto Carlos García Cruz\&. 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
'%A %d-%m-%Y' 1-6-2023 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
