.TH "Main.Main" 3 "Sun Jul 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.Main
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBcontrolador\fP = \fBControlador\fP()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
