.TH "Modelo.Modelo.Modelo" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modelo.Modelo.Modelo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBleer_dataset_entrenamiento\fP (self, direccion_entrenamiento)"
.br
.ti -1c
.RI "def \fBleer_dataset_prueba\fP (self, direccion_prueba)"
.br
.ti -1c
.RI "def \fBget_datos_entrenamiento\fP (self)"
.br
.ti -1c
.RI "def \fBget_datos_pruebas\fP (self)"
.br
.ti -1c
.RI "def \fBget_array_variables\fP (self)"
.br
.ti -1c
.RI "def \fBset_variables\fP (self, array_variables, vista)"
.br
.ti -1c
.RI "def \fBseleccionar_bag_words\fP (self, tipo)"
.br
.ti -1c
.RI "def \fBseleccionar_algoritmo\fP (self, tipo)"
.br
.ti -1c
.RI "def \fBlimpiar_datasets\fP (self)"
.br
.ti -1c
.RI "def \fBestan_limpios_datasets\fP (self)"
.br
.ti -1c
.RI "def \fBlimpiar_sentencias\fP (self, dataset)"
.br
.ti -1c
.RI "def \fBentrenamiento\fP (self)"
.br
.ti -1c
.RI "def \fBclasificar\fP (self)"
.br
.ti -1c
.RI "def \fBverificar_dataframe\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdataset_entrenamiento_\fP"
.br
.ti -1c
.RI "\fBdataset_prueba_\fP"
.br
.ti -1c
.RI "\fBprocesador_\fP"
.br
.ti -1c
.RI "\fBclasificador_\fP"
.br
.ti -1c
.RI "\fBcolumna_extracto\fP"
.br
.ti -1c
.RI "\fBcolumna_tematica\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
