.TH "Modelo.Clasificacion.Clasificador.Clasificador" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modelo.Clasificacion.Clasificador.Clasificador
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBModelo\&.Clasificacion\&.ClasificadorAR\&.ClasificadorAR\fP, and \fBModelo\&.Clasificacion\&.ClasificadorML\&.ClasificadorML\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBget_n_tematicas\fP (self)"
.br
.ti -1c
.RI "def \fBset_n_tematicas\fP (self, n_tematicas)"
.br
.ti -1c
.RI "def \fBget_alfa\fP (self)"
.br
.ti -1c
.RI "def \fBset_alfa\fP (self, alfa)"
.br
.ti -1c
.RI "def \fBget_bag_words\fP (self)"
.br
.ti -1c
.RI "def \fBset_bag_words\fP (self, bag_words)"
.br
.ti -1c
.RI "def \fBget_modelo\fP (self)"
.br
.ti -1c
.RI "def \fBset_modelo\fP (self, modelo)"
.br
.ti -1c
.RI "def \fBset_dataset\fP (self, dataset)"
.br
.ti -1c
.RI "def \fBcrear_array_tematicas\fP (self, clases, probabilidades)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdataset_\fP"
.br
.ti -1c
.RI "\fBbag_words_\fP"
.br
.ti -1c
.RI "\fBmodelo_\fP"
.br
.ti -1c
.RI "\fBalfa_\fP"
.br
.ti -1c
.RI "\fBn_tematicas\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
