.TH "Modelo.Lectura.Lector_CSV.LectorCSV" 3 "Sun Jul 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modelo.Lectura.Lector_CSV.LectorCSV
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModelo\&.Lectura\&.Lector\&.Lector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.RI "Constructor de \fBLectorCSV\fP\&. "
.ti -1c
.RI "def \fBleer\fP (self, direccion)"
.br
.RI "Lee el contenido del archivo csv indicado\&. "
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.RI "Método toString de la clase\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Modelo\&.Lectura\&.Lector_CSV\&.LectorCSV\&.__init__ ( self)"

.PP
Constructor de \fBLectorCSV\fP\&. 
.PP
Reimplemented from \fBModelo\&.Lectura\&.Lector\&.Lector\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def Modelo\&.Lectura\&.Lector_CSV\&.LectorCSV\&.__str__ ( self)"

.PP
Método toString de la clase\&. " 
.PP
\fBReturns\fP
.RS 4
[String] 
.RE
.PP

.PP
Reimplemented from \fBModelo\&.Lectura\&.Lector\&.Lector\fP\&.
.SS "def Modelo\&.Lectura\&.Lector_CSV\&.LectorCSV\&.leer ( self,  direccion)"

.PP
Lee el contenido del archivo csv indicado\&. 
.PP
\fBParameters\fP
.RS 4
\fIdireccion\fP [String] Dirección del archivo a leer\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
