.TH "Modelo.Clasificacion.ClasificadorAR.ClasificadorAR" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Modelo.Clasificacion.ClasificadorAR.ClasificadorAR
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModelo\&.Clasificacion\&.Clasificador\&.Clasificador\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBentrenar_modelo\fP (self, columna_extracto, columna_tematica)"
.br
.ti -1c
.RI "def \fBclasificar_sentencias\fP (self, dataset, columna_extracto)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Modelo\&.Clasificacion\&.ClasificadorAR\&.ClasificadorAR\&.__init__ ( self)"

.PP
Reimplemented from \fBModelo\&.Clasificacion\&.Clasificador\&.Clasificador\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
