.TH "Vista.App.App" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vista.App.App
.SH SYNOPSIS
.br
.PP
.PP
Inherits tk\&.Tk\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBiniciar_frame\fP (self)"
.br
.ti -1c
.RI "def \fBget_frame\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_archivo\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_opciones\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_configuracion\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_ayuda\fP (self)"
.br
.ti -1c
.RI "def \fBget_combobox_algoritmo\fP (self)"
.br
.ti -1c
.RI "def \fBget_combobox_bag\fP (self)"
.br
.ti -1c
.RI "def \fBget_boton_variables\fP (self)"
.br
.ti -1c
.RI "def \fBget_array_variables\fP (self)"
.br
.ti -1c
.RI "def \fBcrear_barra_menu\fP (self)"
.br
.ti -1c
.RI "def \fBabrir_ventana_dialogo\fP (self, frame_padre, array_variables)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBframe\fP"
.br
.ti -1c
.RI "\fBventana_input\fP"
.br
.ti -1c
.RI "\fBboton_variables\fP"
.br
.ti -1c
.RI "\fBentrada_texto_tematicas\fP"
.br
.ti -1c
.RI "\fBentrada_texto_probs\fP"
.br
.ti -1c
.RI "\fBentrada_texto_extracto\fP"
.br
.ti -1c
.RI "\fBbarra_menu\fP"
.br
.ti -1c
.RI "\fBmenu_archivo\fP"
.br
.ti -1c
.RI "\fBmenu_configuracion\fP"
.br
.ti -1c
.RI "\fBmenu_opciones\fP"
.br
.ti -1c
.RI "\fBmenu_ayuda\fP"
.br
.ti -1c
.RI "\fBentrada_texto_n_tematicas\fP"
.br
.ti -1c
.RI "\fBentrada_texto_tematica\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
