.TH "Vista.Vista.Vista" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vista.Vista.Vista
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.RI "Constructor de vista\&. "
.ti -1c
.RI "def \fBiniciar\fP (self)"
.br
.ti -1c
.RI "def \fBget_combobox_algoritmo\fP (self)"
.br
.ti -1c
.RI "def \fBget_combobox_bag\fP (self)"
.br
.ti -1c
.RI "def \fBget_boton_variables\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_archivo\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_opciones\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_configuracion\fP (self)"
.br
.ti -1c
.RI "def \fBget_menu_ayuda\fP (self)"
.br
.ti -1c
.RI "def \fBget_variables\fP (self)"
.br
.ti -1c
.RI "def \fBmostrar_ventana_input\fP (self, array_variables)"
.br
.ti -1c
.RI "def \fBmostrar_ventana_mensaje\fP (self, mensaje)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBapp_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
