.TH "Vista.MainFrame.MainFrame" 3 "Fri Jun 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vista.MainFrame.MainFrame
.SH SYNOPSIS
.br
.PP
.PP
Inherits ttk\&.Frame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, container)"
.br
.RI "Constructor de Mainframe, en el se construye toda la interfaz de usuario del frame principal\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimagen_ull\fP"
.br
.ti -1c
.RI "\fBimg\fP"
.br
.ti -1c
.RI "\fBlabel_imagen\fP"
.br
.ti -1c
.RI "\fBcombo_bag\fP"
.br
.ti -1c
.RI "\fBcombo_algoritmo\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def Vista\&.MainFrame\&.MainFrame\&.__init__ ( self,  container)"

.PP
Constructor de Mainframe, en el se construye toda la interfaz de usuario del frame principal\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontainer\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
