.TH "Vista.App.App" 3 "Sun Jul 2 2023" "Version 1.0" "TFG-023" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vista.App.App
.SH SYNOPSIS
.br
.PP
.PP
Inherits tk\&.Tk\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.RI "Constructor de \fBApp\fP\&. "
.ti -1c
.RI "def \fBcrear_app\fP (self)"
.br
.RI "Construye y junta todos los elementos visuales de la aplicación\&. "
.ti -1c
.RI "def \fBmostrar_app\fP (self)"
.br
.RI "Muestra el frame de la aplicación\&. "
.ti -1c
.RI "def \fBget_frame\fP (self)"
.br
.RI "Devuelve el propio frame de la app\&. "
.ti -1c
.RI "def \fBget_menu_archivo\fP (self)"
.br
.RI "Devuelve el menú específico del apartado 'Archivo'\&. "
.ti -1c
.RI "def \fBget_menu_opciones\fP (self)"
.br
.RI "Devuelve el menú específico del apartado 'Opciones'\&. "
.ti -1c
.RI "def \fBget_menu_configuracion\fP (self)"
.br
.RI "Devuelve el menú específico del apartado 'Configuración'\&. "
.ti -1c
.RI "def \fBget_menu_ayuda\fP (self)"
.br
.RI "Devuelve el menú específico del apartado 'Ayuda'\&. "
.ti -1c
.RI "def \fBget_combobox_algoritmo\fP (self)"
.br
.RI "Devuelve el combo de los algoritmos del Mainframe\&. "
.ti -1c
.RI "def \fBget_combobox_bag\fP (self)"
.br
.RI "Devuelve el combo de las bolsas de palabras del Mainframe\&. "
.ti -1c
.RI "def \fBget_boton_configuracion\fP (self)"
.br
.RI "Devuelve el botón de 'Aplicar cambios' de la ventana de configuración\&. "
.ti -1c
.RI "def \fBget_variables_configuracion\fP (self)"
.br
.RI "Devuelve las variables de configuración actual de la ventana de configuración\&. "
.ti -1c
.RI "def \fBcrear_barra_menu\fP (self)"
.br
.RI "Crea el menú de la barra superior de la aplicación\&. "
.ti -1c
.RI "def \fBcrear_ventana_configuracion\fP (self, frame_padre, variables_configuracion)"
.br
.RI "Crea la ventana auxiliar del apartado de configuración\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def Vista\&.App\&.App\&.crear_ventana_configuracion ( self,  frame_padre,  variables_configuracion)"

.PP
Crea la ventana auxiliar del apartado de configuración\&. 
.PP
\fBParameters\fP
.RS 4
\fIframe_padre\fP [Frame] Frame principal\&. 
.br
\fIvariables_configuracion\fP [Array] Variables de la configuración actual del apartado de configuración\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_boton_configuracion ( self)"

.PP
Devuelve el botón de 'Aplicar cambios' de la ventana de configuración\&. 
.PP
\fBReturns\fP
.RS 4
[Button] Botón de aplicar cambios de la ventana de configuración\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_combobox_algoritmo ( self)"

.PP
Devuelve el combo de los algoritmos del Mainframe\&. 
.PP
\fBReturns\fP
.RS 4
[ComboBox] Combo de los algoritmos a elegir\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_combobox_bag ( self)"

.PP
Devuelve el combo de las bolsas de palabras del Mainframe\&. 
.PP
\fBReturns\fP
.RS 4
[ComboBox] Combo de las bolsas de palabras a elegir\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_frame ( self)"

.PP
Devuelve el propio frame de la app\&. 
.PP
\fBReturns\fP
.RS 4
[Frame] Frame de la app\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_menu_archivo ( self)"

.PP
Devuelve el menú específico del apartado 'Archivo'\&. 
.PP
\fBReturns\fP
.RS 4
[Menu] Menú del apartado 'Archivo'\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_menu_ayuda ( self)"

.PP
Devuelve el menú específico del apartado 'Ayuda'\&. 
.PP
\fBReturns\fP
.RS 4
[Menu] Menú del apartado 'Ayuda'\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_menu_configuracion ( self)"

.PP
Devuelve el menú específico del apartado 'Configuración'\&. 
.PP
\fBReturns\fP
.RS 4
[Menu] Menú del apartado 'Configuración'\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_menu_opciones ( self)"

.PP
Devuelve el menú específico del apartado 'Opciones'\&. 
.PP
\fBReturns\fP
.RS 4
[Menu] Menú del apartado 'Opciones'\&. 
.RE
.PP

.SS "def Vista\&.App\&.App\&.get_variables_configuracion ( self)"

.PP
Devuelve las variables de configuración actual de la ventana de configuración\&. 
.PP
\fBReturns\fP
.RS 4
[Array] Variables de la configuración\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TFG-023 from the source code\&.
